name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: visaapp-447008

    - name: Create Kubernetes Cluster
      run: |
        gcloud container clusters create visa-app-cluster \
          --zone us-central1-a \
          --num-nodes 3 \
          --enable-autoscaling --min-nodes 1 --max-nodes 5 \
          --project visaapp-447008
          
    - name: Get Kubeconfig and Set as Secret
      run: |
        KUBECONFIG_CONTENT=$(gcloud container clusters get-credentials visa-app-cluster --zone us-central1-a --project visaapp-447008 --format json | jq -r .kubeconfig)
        echo "KUBECONFIG_CONTENT=${KUBECONFIG_CONTENT}" >> $GITHUB_ENV

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 --tag gcr.io/visaapp-447008/visa-app-checker:v1 --push .

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
