name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: visaapp-447008

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 --tag gcr.io/visaapp-447008/visa-app-checker:v1 --push .

    # Eğer daha önce cluster yoksa, oluşturulacaksa burada cluster oluşturulabilir:
    - name: Create GKE Cluster (if needed)
      run: |
        gcloud container clusters create visa-app-cluster \
          --disk-size=100GB \
          --zone us-central1-a \
          --num-nodes=3  # Burada ihtiyacınıza göre node sayısını ve disk boyutunu değiştirebilirsiniz.

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
