name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: visaapp-447008

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Check if Cluster Exists and Connect
      run: |
        if gcloud container clusters describe visa-app-cluster --zone us-central1-a --project visaapp-447008 > /dev/null 2>&1; then
          echo "Cluster already exists. Connecting..."
        else
          echo "Cluster does not exist. Creating a new one..."
          gcloud container clusters create visa-app-cluster \
            --zone us-central1-a \
            --num-nodes 3 \
            --enable-autoscaling --min-nodes 1 --max-nodes 5 \
            --project visaapp-447008
        fi

    - name: Get Cluster Credentials
      run: |
        gcloud container clusters get-credentials visa-app-cluster --zone us-central1-a --project visaapp-447008

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        gcloud container clusters get-credentials visa-app-cluster --zone us-central1-a --project visaapp-447008
        echo "Kubeconfig updated"

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 --tag gcr.io/visaapp-447008/visa-app-checker:v1 --push .

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false