name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: visaapp-447008
        export_default_credentials: true

    - name: Check if GKE Cluster exists
      id: cluster_check
      run: |
        if gcloud container clusters describe visa-app-cluster --region us-central1 > /dev/null 2>&1; then
          echo "Cluster exists"
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "Cluster does not exist"
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Create GKE Cluster if not exists
      if: env.exists == 'false'
      run: |
        gcloud container clusters create visa-app-cluster \
          --region us-central1 \
          --num-nodes 2 \
          --quiet

    - name: Configure kubectl for GKE
      run: |
        gcloud container clusters get-credentials visa-app-cluster --region us-central1

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 --tag gcr.io/visaapp-447008/visa-app-checker:v1 --push .

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
